name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: test
        run: npm run test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build

      - name: Run playwright tests
        run: npx playwright test
        
      - name: Deploy to Fly.io
        if: ${{ github.event_name == 'push' && !contains(github.event.commits.*.message, '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
      needs: [simple_deployment_pipeline]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
        - name: Bump version and push tag
          if: ${{ github.event_name == 'push' && !contains(github.event.commits.*.message, '#skip') }}
          uses: anothrNick/github-tag-action@1.67.0
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
           WITH_V: true
